name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  publish:
<<<<<<< HEAD
    runs-on: ubuntu-latest
=======
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
>>>>>>> dad2c1b... Fix CI failure with i386 caused by latest Ubuntu version. Pin Ubuntu version to allow us to upgrade in the future. (#56447)
    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Docker Image to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tgstation/tgstation
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "latest"
          cache: true
